name: Build and test

on:
  pull_request:
    branches:
      - 'main'
      - 'release*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Run Maven build
        run: mvn clean test
